version: "2"
services:
  test:
    build: .
    volumes:
      - "./test:/test"
      - "./resource:/opt/resource"
    working_dir: /opt/resource
    command:
      - "/test/run"
      - "/test/check.request.json"
